import externalfunctions
# On importe les fonctions nécéssaire à certaines règles 

# la liste des règles
rules = [
    # Règle par défaut quand le bot ne connais pas de réponse paramétrée
    { 
        "id": "Je sais pas",
        "rule": ".*",
        "response": "Désolé, je ne sais pas, dite moi ce que vous souhaitez que je réponde dans ce cas.",
        "score": 0,
        "fatal": False,
        "function": externalfunctions.RecordNewResponse,
    },
    # Autres régles
    {
        "id": "Bonjour",
        "rule": "bonjour",
        "response": "Bonjour, je suis votre spécialiste en burger, en quoi puis-je vous aider ?",
        "score": 1,
        "fatal": False,
        "function": None,
    },
    {
        "id": "Aurevoir",
        "rule": "[au revoir]|[aurevoir]",
        "response": "Ravi d'avoir pu vous aider.",
        "score": 1,
        "fatal": True,
        "function": None,
    },
    {
        "id": "Salut",
        "rule": "[salut|hello]",
        "response": "Salut, comment va tu ? Une question sur les burgers ?",
        "score": 1,
        "fatal": False,
        "function": None,
    },
    {
        "id":"apropos",
        "rule":"(qu'est ce qu'|c'est quoi |qu'est ce que c'est |Qu'est ce que c'est qu')un (burger|hamburger).*",
        "response":"Un hamburger, ou par aphérèse burger, est un sandwich d'origine allemande, composé de deux pains de forme ronde1 (bun) généralement garnis d'une galette de steak haché (généralement du bœuf) et de crudités, salade, tomate, oignon, cornichon (pickles) ainsi que de sauce. D'autres question à ce propos ?",
        "score":1,
        "fatal":False,
        "function":None,
    },
    {
        "id":"date",
        "rule":".* (année est (apparu|inventé)|(de quand date)|(date (d'invention|de création|d'apparition))) (du|le) (burger|hamburger).*",
        "response":"Le burger est inventé en 1758 en Allemagne à Hambourg. N'hésitez pas à me poser des questions sur l'hétymologie du mot hamburger.",
        "score":1,
        "fatal":False,
        "function":None,
    },
    {
        "id":"ethymo",
        "rule":".*hétymologie (du mot|de) (burger|hamburger).*",
        "response":"Hamburger fait référence à la ville de Hambourg, en Allemagne. Il n'existe aucun rapport étymologique entre le hamburger et le jambon (en anglais : ham), puisque le nom de la ville de Hambourg a une étymologie différente. Une question sur la date d'invention du burger ?",
        "score":1,
        "fatal":False,
        "function":None,
    },
    {
        "id":"découverte",
        "rule":".*(donne moi un (exemple de|)|est le) (burger|hamburger) (le plus |)connu.*",
        "response":"Le burger le plus connu est certainement le Big Mac, de la chaine de restauration rapide McDonald's. Mais je peux vous trouver un burger plus original si vous me le demandez.",
        "score":1,
        "fatal":False,
        "function":None,
    },
    {
        "id":"original",
        "rule":".*(donne moi un (exemple de|)|est le) (burger|hamburger) (le plus |)(original|spécial|innatendu).*",
        "response":"Bien sûr !  L’Atomic Fallout, l’emblématique burger servi à l’Atomic Burger de Bristol, est tellement pimenté que les clients doivent signer une exonération de responsabilité, porter des gants de protection, ou encore prouver qu’ils ont plus de 18 ans et sont sobres avant de se mettre à table. Mais il est loin d'être le plus gros burger du monde...",
        "score":1,
        "fatal":False,
        "function":None, 
    },
    {
        "id":"biggest",
        "rule":".*(donne moi un (exemple de|)|est le) (burger|hamburger) (le plus |)(grand|gros|énorme).*",
        "response":"C'est le Black Bear Casino Resort de Carlton dans le Minnesota aux Etats-Unis. Le double bacon cheeseburger comprend 27 kg de bacon, 22 kg de laitue et de 18 kg de fromage et cornichons pour un total de 913 kilos et près de quatre millions de calories.",
        "score":1,
        "fatal":False,
        "function":None, 
    },
    {
        "id":"Shojo",
        "rule":"Explique moi ce qu'est un manga shojo",
        "response":"",
        "score":1,
        "fatal":False,
        "function":None, 
    },
    {
        "id":"Shonen",
        "rule":"Explique moi ce qu'est un manga shonen",
        "response":"Un manga shonen est un des trois types de mangas qui existent et où l'intrigue principale suit un personnage (souvent masculin) dans une aventure pour atteindre un objectif.",
        "score":1,
        "fatal":False,
        "function":None,
    },
    {
        "id":"Seinen",
        "rule":"Explique moi ce qu'est un manga seinen",
        "response":"",
        "score":1,
        "fatal":False,
        "function":None,
    },
]